


```{r}
significant_NR_genes <- dgeResults[["NR_effect"]] %>% 
  filter(FDR < 0.05)

NR_genes <- final_matrix %>% 
  filter(rownames(final_matrix) %in% significant_NR_genes$rn)

  heatmap <- pheatmap(NR_genes,
                      treeheight_col = 0,
                      treeheight_row = 0,
                      scale = "row",
                      legend = T,
                      na_col = "white",
                      Colv = NA,
                      na.rm = T,
                      cluster_cols = F,
                      fontsize_row = 1,
                      fontsize_col = 3,
                      cellwidth = 3,
                      cellheight = 1,
                      main = "Genes affected by NR"
  )
  heatmap
  ggsave(heatmap, filename = here("data/figures/NAD_heatmap_significant.png"), scale = 1)

volcano_genes <- significant_NR_genes %>% 
  filter(logFC >5)
  
volcano_plot <-  ggplot(significant_NR_genes, aes(x = logFC, y = -log10(FDR))) +
    geom_point()+
  geom_text(aes(x = logFC, y = -log10(FDR), label = rn), data = significant_NR_genes[significant_NR_genes$rn %in% volcano_genes$rn,],
             nudge_x = 0.02,
              nudge_y = 0.05,
              check_overlap = T)

 ggsave(volcano_plot, filename = here("data/figures/NAD_terms.png"), scale = 2.5)
  
```

```{r}

heatmap_generator <- function(count_matrix){
  Selected_candidates <- c("ADAMTS14",
"PRND",
"COL1A1",
"MXRA5Y",
"DES",
"PTX3",
"LRRTM4",
"CXCL11",
"LIPG",
"NR4A1AS",
"GOLGA5P1",
"APLN",
"KCNU1",
"SLC2A5",
"CXCL10",
"DCX",
"CHI3L2",
"CHST1",
"AC134312.1",
"LILRA5",
"ABCB5",
"SIGLEC10",
"ELOVL6",
"ADCYAP1",
"SERPINA1",
"PYCR1",
"AC253576.2",
"FLG2"
)
  Selected_candidates <- as.data.table(Selected_candidates)
  setnames(Selected_candidates, "Selected_candidates", "Gene")

  Candidates_raw <- count_matrix%>%
    filter(rownames(count_matrix) %in% Selected_candidates$Gene)
 Candidate_groups <- setup %>% 
   dplyr::select(ID, Group) 

   rownames(Candidate_groups) = Candidate_groups$ID
 Candidate_groups <- Candidate_groups %>% 
   dplyr::select(-ID)
    heatmap <- pheatmap(Candidates_raw,
                      treeheight_col = 0,
                      treeheight_row = 0,
                      scale = "row",
                      legend = T,
                      na_col = "white",
                      Colv = NA,
                      na.rm = T,
                      cluster_cols = F,
                      fontsize_row = 5,
                      fontsize_col = 5,
                      cellwidth = 5,
                      cellheight = 7,
                      annotation_col = Candidate_groups
  )
  ggsave(heatmap, filename = here::here("data/figures/Test_heatmap.png"), scale = 1.5)
  heatmap
  

}



```

```{r}


Candidates_for_sum <- Candidates_raw %>% 
  mutate(Gene = rownames(Candidates_raw))

raw_data_tidy <- pivot_longer(Candidates_for_sum, names_to = "ID",
              values_to = "abundance",
             cols= -Gene)
View(raw_data_tidy)

raw_data_plot <- inner_join(raw_data_tidy, setup)

raw_data_plot <- as.data.frame(raw_data_plot)
raw_data_plot <- raw_data_plot %>%
  dplyr::select(-Group)

summary_candidates_raw <- summarySE(raw_data_plot,
                                measurevar = "abundance",
                                groupvars = c("Gene", "Time", "Treatment"),
                                na.rm = T) %>%
  unite(Group, Time, Treatment, sep = "_", remove = F)


ggplot(summary_candidates_raw,
       aes(x = Group, 
           y = abundance, 
           fill = Group))+
  geom_col()+
  facet_wrap(~Gene)

summary_candidates_raw$Group  <- factor(summary_candidates_raw$Group, levels = c("A_Placebo", "A_NR", "B_Placebo", "B_NR"))

Flg2 <- 
  ggplot(subset(summary_candidates_raw, Gene == "FLG2"), 
       aes(x = Group, 
           y = abundance))+
  geom_col()+
  ggtitle("FLG2")+
  geom_errorbar(aes(ymin=abundance-se, 
                    ymax = abundance+se), 
                width = .1) 

Adamts14 <- 
  ggplot(subset(summary_candidates_raw, Gene == "ADAMTS14"), 
       aes(x = Group, 
           y = abundance))+
  geom_col()+
  ggtitle("Adamts14")+
  geom_errorbar(aes(ymin=abundance-se, 
                    ymax = abundance+se), 
                width = .1) 



Adamts14
Flg2


```
```{r}


PCA_plots <-
    gridExtra::grid.arrange(ncol = 1, pBase, pBase2, pBase3)
  ggplot2::ggsave(PCA_plots, filename = here("data/figures/QCplots/.png"))






```


```{r}

  heatmap_generator <- function(count_matrix){
  Selected_candidates <- c("IL7R",
"LEF1",
"ACSL6",
"CD2",
"PIM2",
"MS4A1",
"HEMGN",
"SELL",
"TRIM69",
"BTLA",
"CD3E",
"TRBC2",
"ITK",
"CST7",
"GBP5",
"POP1",
"CXCR4",
"SORL1",
"PF4",
"ANKRD36BP2",
"PADI2",
"ARHGAP15",
"SIDT1",
"CLEC4E",
"HBB",
"CCR4",
"RHOH",
"FCGR3B",
"SNORA71B",
"CAMK4",
"TRAT1",
"THEMIS",
"RASSF8-AS1",
"CYFIP2",
"BTN3A2",
"TENT5C",
"MGAM"
)
  
  
  
  Selected_candidates <- as.data.table(Selected_candidates)
  setnames(Selected_candidates, "Selected_candidates", "Gene")

  Candidates_raw <- count_matrix%>%
    filter(rownames(count_matrix) %in% Selected_candidates$Gene)
 Candidate_groups <- setup %>% 
   dplyr::select(ID, Group) 

   rownames(Candidate_groups) = Candidate_groups$ID
 Candidate_groups <- Candidate_groups %>% 
   dplyr::select(-ID)

 


 
   rownames(Candidate_groups) = Candidate_groups$ID
 Candidate_groups <- Candidate_groups %>% 
   dplyr::select(-ID)
    heatmap <- pheatmap(Candidates_raw,
                      treeheight_col = 0,
                      treeheight_row = 0,
                      scale = "row",
                      legend = T,
                      na_col = "white",
                      Colv = NA,
                      na.rm = T,
                      cluster_cols = F,
                      fontsize_row = 5,
                      fontsize_col = 5,
                      cellwidth = 5,
                      cellheight = 7
  )
  ggsave(heatmap, filename = here::here("data/figures/heatmap_CR_largest_FC.png"), scale = 1.5)
  heatmap
  

}



```

```{r}

#' Load metadata and sort them according to count matrix input
#'
#' @param file_name the name of teh metadata file (default "metadata.csv")
#'
#' @return metadata file sorted according to count matrix order

load_metadata <- function(file_name) {
  data_file <- fs::dir_ls(here::here("data-raw/"),
                          regexp = file_name,
                          recurse = T)
  metadata <- openxlsx::read.xlsx(xlsxFile = data_file)
  return(metadata)
}
sample_info <- load_metadata("025_Metadata_Human_realign")
sample_info <- sample_info %>% 
  dplyr::filter(
    !Sample_ID == "025_76" &
      !Sample_ID == "025_77" &
      !Sample_ID == "025_78" &
      !Sample_ID == "025_96" &
      !Sample_ID == "025_79" &
      !Sample_ID == "025_80"
  )



ID_order <- setup_person$ID

sample_info <- sample_info %>% 
  dplyr::filter(Sample_ID %in% setup_person$Sample_ID)

sample_info <- sample_info %>% 
  dplyr::arrange(Sample_ID = factor(Sample_ID, levels = ID_order))

all(sample_info$Sample.ID==colnames(count_matrix))

sample_info <- left_join(sample_info, setup_person, by = "Sample_ID")


test <- filterByExpr(count_matrix, design = design)
count_matrix_test <- count_matrix[test, , keep.lib.sizes = F, keep.rownames = T]

all(sample_info$Sample.ID==colnames(count_matrix_test))
count_matrix_wo_batch <- removeBatchEffect(count_matrix_test, batch = sample_info$ID)

plotMDS(count_matrix_wo_batch, labels = NULL,
    dim.plot = c(1, 2),
    pch = 16,
    main = "MDS with batch correction",
    col = as.numeric(as.factor(sample_info$Group))
  )

View(RNAseq_limma)

boxplot(arrayWeights(RNAseq_limma)~RNAseq_limma$samples$group)
  
 library_pool <- plotMDS(
    RNAseq,
    labels = NULL,
    dim.plot = c(1, 2),
    pch = 16,
    col = as.numeric(as.factor(sample_info$Library.Pool)),
    main = "Library Pool"
  )
  
sequencing_lane <-  plotMDS(RNAseq,
    labels = NULL,
    dim.plot = c(1, 2),
    pch = 16,
    col = as.numeric(as.factor(sample_info$Sequencing.Lane)),
    main = "Sequencing Lane"
  )
  

patient_ID <-  plotMDS(RNAseq,
    labels = NULL,
    dim.plot = c(1, 2),
    pch = 16,
    col = as.numeric(as.factor(sample_info$ID)),
    main = "Patient ID"
  )
  #prøv removebatcheffect
?removeBatchEffect

  
  pdf(file.path(here("data/figures/QCplots"), "MDSplots_after_filter.pdf"), width = 4, height = 4)
  par(mfrow = c(1, 1))
  plot(pBase)
  plot(pBase2)
  plot(pBase3)
  plotMDS(RNAseq, ndim = 3)
  par(mfrow = oldpar)
  dev.off()

```

```{r}
Candidates_for_sum <- Candidates_raw %>% 
  mutate(Gene = rownames(Candidates_raw))

raw_data_tidy <- pivot_longer(Candidates_for_sum, names_to = "ID",
              values_to = "abundance",
             cols= -Gene)
View(raw_data_tidy)

raw_data_plot <- inner_join(raw_data_tidy, setup)

raw_data_plot <- as.data.frame(raw_data_plot)
raw_data_plot <- raw_data_plot %>%
  dplyr::select(-Group)

summary_candidates_raw <- summarySE(raw_data_plot,
                                measurevar = "abundance",
                                groupvars = c("Gene", "Time", "Treatment"),
                                na.rm = T) %>%
  unite(Group, Time, Treatment, sep = "_", remove = F)


ggplot(summary_candidates_raw,
       aes(x = Group, 
           y = abundance, 
           fill = Group))+
  geom_col()+
  facet_wrap(~Gene)

summary_candidates_raw$Group  <- factor(summary_candidates_raw$Group, levels = c("A_Placebo", "A_NR", "B_Placebo", "B_NR"))

Flg2 <- 
  ggplot(subset(summary_candidates_raw, Gene == "FLG2"), 
       aes(x = Group, 
           y = abundance))+
  geom_col()+
  ggtitle("FLG2")+
  geom_errorbar(aes(ymin=abundance-se, 
                    ymax = abundance+se), 
                width = .1) 

Selected_candidates <- c("ENSG00000169994",
"ENSG00000064601",
"ENSG00000072163",
"ENSG00000198099",
"ENSG00000178301",
"ENSG00000175066",
"ENSG00000160193",
"ENSG00000183807",
"ENSG00000241155",
"ENSG00000197776",
"ENSG00000120278",
"ENSG00000114107",
"ENSG00000168685",
"ENSG00000185880",
"ENSG00000136929")

 Selected_candidates <- as.data.table(Selected_candidates)
  setnames(Selected_candidates, "Selected_candidates", "Gene")
  group <- setup_person$Group

  y <- edgeR::DGEList(counts = count_matrix, group = group)
  keep_y <- edgeR::filterByExpr(y, design = design)
  y <- y[keep_y, , keep.lib.sizes = F]
  y<-calcNormFactors(y)
  count_matrix_cpm<- cpm(y, log = T)
   
  
  Candidates_raw <- as.data.frame(count_matrix_cpm)%>%
    dplyr::filter(rownames(count_matrix_cpm) %in% Selected_candidates$Gene) 
  Candidates_raw <- Candidates_raw %>%   
  mutate(Gene = rownames(Candidates_raw)) 
  
  Candidates_raw <- left_join(Candidates_raw, key, by=c("Gene" = "ENSEMBL"))%>% 
    dplyr::select(-Gene)

raw_data_tidy <- pivot_longer(Candidates_raw, names_to = "ID",
              values_to = "countse",
             cols= -SYMBOL)
raw_data_plot <- left_join(raw_data_tidy, setup, by = c("ID" = "Sample_ID"))
 
 
summary_candidates_raw <- summarySE(raw_data_plot,
                                measurevar = "countse",
                                groupvars = c("SYMBOL", "Group"),
                                na.rm = T)



plots <- ggplot(summary_candidates_raw,
       aes(x = Group, 
           y = countse, 
           fill = Group))+
  geom_col()+
  facet_wrap(~SYMBOL)
 

ggsave(plots,
    filename = here("data/figures/top3_CPM_Limma genes.png"),
    width = 12,
    height = 12,
    units = "cm"
  )
 

selected_genes_voom <- c("ENSG00000064601",
"ENSG00000175066",
"ENSG00000169994",
"ENSG00000234215",
"ENSG00000156587",
"ENSG00000246695",
"ENSG00000175155",
"ENSG00000203326",
"ENSG00000171843",
"ENSG00000197776",
"ENSG00000161091",
"ENSG00000114107",
"ENSG00000118689",
"ENSG00000156587",
"ENSG00000203326")
Selected_candidates <- as.data.table(selected_genes_voom)
setnames(Selected_candidates, "selected_genes_voom", "Gene")

y <- edgeR::DGEList(counts = count_matrix, group = group)
  keep_y <- edgeR::filterByExpr(y, design = design)
  y <- y[keep_y, , keep.lib.sizes = F]
  y<-calcNormFactors(y)
  count_matrix_cpm<- cpm(y, log = T)

Candidates_raw <- as.data.frame(count_matrix)%>%
    dplyr::filter(rownames(count_matrix) %in% Selected_candidates$Gene) 
  Candidates_raw <- Candidates_raw %>%   
  mutate(Gene = rownames(Candidates_raw)) 
  
  Candidates_raw <- left_join(Candidates_raw, key, by=c("Gene" = "ENSEMBL"))%>% 
    dplyr::select(-Gene)

raw_data_tidy <- pivot_longer(Candidates_raw, names_to = "ID",
              values_to = "countse",
             cols= -SYMBOL)
raw_data_plot <- left_join(raw_data_tidy, setup, by = c("ID" = "Sample_ID"))
 
 library(Rmisc)
summary_candidates_raw <- summarySE(raw_data_plot,
                                measurevar = "countse",
                                groupvars = c("SYMBOL", "Group"),
                                na.rm = T)



plots <- ggplot(summary_candidates_raw,
       aes(x = Group, 
           y = countse, 
           fill = Group))+
  geom_col()+
  facet_wrap(~SYMBOL)

selected_genes_voom_limma <- c("ENSG00000200792",
"	ENSG00000077984",
"ENSG00000175066",
"ENSG00000234215",
"ENSG00000169994",
"ENSG00000178301",
"ENSG00000156587",
"ENSG00000163249",
"ENSG00000241155",
"ENSG00000160193",
"ENSG00000231871",
"ENSG00000114107",
"ENSG00000118689",
"ENSG00000156587",
"ENSG00000203326")
Selected_candidates_limma <- as.data.table(selected_genes_voom_limma)
setnames(Selected_candidates_limma, "selected_genes_voom_limma", "Gene")

Candidates_raw <- as.data.frame(count_matrix_cpm)%>%
    dplyr::filter(rownames(count_matrix) %in% Selected_candidates_limma$Gene) 
  Candidates_raw <- Candidates_raw %>%   
  mutate(Gene = rownames(Candidates_raw)) 
  
  Candidates_raw <- left_join(Candidates_raw, key, by=c("Gene" = "ENSEMBL"))%>% 
    dplyr::select(-Gene)

raw_data_tidy <- pivot_longer(Candidates_raw, names_to = "ID",
              values_to = "countse",
             cols= -SYMBOL)
raw_data_plot <- left_join(raw_data_tidy, setup, by = c("ID" = "Sample_ID"))
 
 library(Rmisc)
summary_candidates_raw <- summarySE(raw_data_plot,
                                measurevar = "countse",
                                groupvars = c("SYMBOL", "Group"),
                                na.rm = T)



plots <- ggplot(summary_candidates_raw,
       aes(x = Group, 
           y = countse, 
           fill = Group))+
  geom_col()+
  facet_wrap(~SYMBOL)

```


```{r}
#investigate effect in PR group
setup_person_sub <- setup_person %>%  
  dplyr::filter(Condition2 == "PR")
subset_matrix <- as.data.table(count_matrix_limma$E)

subset_matrix <- subset_matrix %>% 
  dplyr::select(setup_person_sub$Sample_ID)

plot <- plotMDS(subset_matrix, labels = NULL,
        dim.plot = c(1, 2),
        pch = 16,
        main = "MDS for PR_samples",
        col = as.numeric(as.factor(setup_person_sub$Group))
)

mdsData <- plotMDS(subset_matrix,
                   ndim = 3, plot = F)

mdsData <-
  mdsData$cmdscale.out %>% data.table(keep.rownames = TRUE) %>%
  mutate(ID = rownames(setup_person_sub$Sample_ID)) %>%
  dplyr::select(-rn) %>%
  mutate(Group = setup_person_sub$ID)

setnames(mdsData, c("V1","V2", "V3"),c("dim1","dim2", "dim3"))
 plot1 <- ggplot(mdsData, aes(x = dim1, y = dim2, colour = Group)) +
   geom_point(size = 5) +
   #geom_label(show.legend = FALSE, size = 5) +
   theme_bw()

 #investigate effect at baseline
 setup_person_sub <- setup_person %>%  
  dplyr::filter(Condition1 == "A")
subset_matrix <- as.data.table(count_matrix_limma$E)

subset_matrix <- subset_matrix %>% 
  dplyr::select(setup_person_sub$Sample_ID)

plot <- plotMDS(subset_matrix, labels = NULL,
        dim.plot = c(1, 2),
        pch = 16,
        main = "MDS for PR_samples",
        col = as.numeric(as.factor(setup_person_sub$Group))
)

mdsData <- plotMDS(subset_matrix,
                   ndim = 3, plot = F)

mdsData <-
  mdsData$cmdscale.out %>% data.table(keep.rownames = TRUE) %>%
  mutate(ID = rownames(setup_person_sub$Sample_ID)) %>%
  dplyr::select(-rn) %>%
  mutate(Group = setup_person_sub$Gender)

setnames(mdsData, c("V1","V2", "V3"),c("dim1","dim2", "dim3"))
 plot1 <- ggplot(mdsData, aes(x = dim1, y = dim2, colour = Group)) +
   geom_point(size = 5) +
   #geom_label(show.legend = FALSE, size = 5) +
   theme_bw()

plot1 
 #investigate effect of blood glucose levels in PR group
setup_person_sub <- setup_person %>%  
  dplyr::filter(Condition2 == "PR") 


clinical_data_sub <- clinical_data 
colnames(clinical_data_sub)[2]<-"Glucose"
clinical_data_sub <- clinical_data_sub %>% 
dplyr::filter(Sample.ID %in% setup_person_sub$Sample_ID) %>% 
  dplyr::mutate(Glucose_levels = case_when(Glucose < 200 ~ "<200 mg/dL",
                                           Glucose >200 ~ ">200 mg/dL")
    
  )

subset_matrix <- as.data.table(count_matrix_limma$E)

subset_matrix <- subset_matrix %>% 
  dplyr::select(setup_person_sub$Sample_ID)

plot <- plotMDS(subset_matrix, labels = NULL,
        dim.plot = c(1, 2),
        pch = 16,
        main = "MDS for PR_samples",
        col = as.numeric(as.factor(setup_person_sub$Group))
)

mdsData <- plotMDS(subset_matrix,
                   ndim = 3, plot = F)

mdsData <-
  mdsData$cmdscale.out %>% data.table(keep.rownames = TRUE) %>%
  mutate(ID = rownames(setup_person_sub$Sample_ID)) %>%
  dplyr::select(-rn) %>%
  mutate(Group = clinical_data_sub$)

setnames(mdsData, c("V1","V2", "V3"),c("dim1","dim2", "dim3"))
 plot1 <- ggplot(mdsData, aes(x = dim1, y = dim2, colour = Group)) +
   geom_point(size = 5) +
   #geom_label(show.legend = FALSE, size = 5) +
   theme_bw()

plot1 

 #investigate effect at baseline
 setup_person_sub <- setup_person %>%  
  dplyr::filter(Condition2 == "CR")
subset_matrix <- as.data.table(count_matrix_limma$E)

subset_matrix <- subset_matrix %>% 
  dplyr::select(setup_person_sub$Sample_ID)

plot <- plotMDS(subset_matrix, labels = NULL,
        dim.plot = c(1, 2),
        pch = 16,
        main = "MDS for PR_samples",
        col = as.numeric(as.factor(setup_person_sub$Group))
)

mdsData <- plotMDS(subset_matrix,
                   ndim = 3, plot = F)

mdsData <-
  mdsData$cmdscale.out %>% data.table(keep.rownames = TRUE) %>%
  mutate(ID = rownames(setup_person_sub$Sample_ID)) %>%
  dplyr::select(-rn) %>%
  mutate(Group = setup_person_sub$Group)

setnames(mdsData, c("V1","V2", "V3"),c("dim1","dim2", "dim3"))
 plot1 <- ggplot(mdsData, aes(x = dim1, y = dim2, colour = Group)) +
   geom_point(size = 5) +
   #geom_label(show.legend = FALSE, size = 5) +
   theme_bw()

plot1 

```

```{r}
candidates <- c("ENSG00000116044", "ENSG00000142168", "ENSG00000285441", "ENSG00000109610", "ENSG00000181929", "ENSG00000128829", "ENSG00000096717", "ENSG00000142082", "ENSG00000172071", "ENSG00000128272", "ENSG00000175197", "ENSG00000118217", "ENSG00000181092", "ENSG00000109819", "ENSG00000132170", "ENSG00000181856", "ENSG00000108064")

cpm_subset <- as.data.frame(cpm_matrix)

cpm_subset <- cpm_subset %>% 
  dplyr::filter(rownames(cpm_subset) %in% candidates)



cpm_subset_long <- cpm_subset %>% 
  dplyr::mutate(Gene = rownames(cpm_subset))%>% 
  pivot_longer(cols = -Gene, names_to = "Participant", values_to = "CPM")

cpm_subset_long <- left_join(cpm_subset_long, key, by=c("Gene" = "ENSEMBL")) %>% 
  dplyr::select(-Gene)

cpm_subset_long <-   left_join(cpm_subset_long, setup_person, by = c("Participant"="Sample_ID"))

Gene_CPM <- ggplot(subset(cpm_subset_long, Condition2=="PR"),
       aes(x = Condition1, 
           y = CPM, 
           color = ID))+
  geom_point()+
  geom_line(aes(group = ID))+
  facet_wrap(~SYMBOL)


Gene_CPM_CR <- ggplot(subset(cpm_subset_long, Condition2=="CR"),
       aes(x = Condition1, 
           y = CPM, 
           color = ID))+
  geom_point()+
  geom_line(aes(group = ID))+
  facet_wrap(~SYMBOL)
```

